### ISSUE TITLE
Incompatible build with foundry 0.3.0

### ISSUE THREAD

**Issue by web3nish** [alchemyplatform/rundler#957]
**Describe the bug**
When setting up new project, foundry 0.3.0 doesn't compile the contract correctly because of which rust compiler panics

**To reproduce**
Install foundry 0.3.0 and run cargo build --all --all-features

**Expected behavior**
Works well with 0.2.0 version. 

**Logs**
Compiling rundler-contracts v0.4.0 (/Users/nish/Documents/Startale/rundler/crates/contracts)
error[E0080]: evaluation of constant value failed
   --> crates/contracts/src/v0_7.rs:254:19
    |
254 |         Err(_) => panic!("Failed to decode entry point simulations hex"),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Failed to decode entry point simulations hex', crates/contracts/src/v0_7.rs:254:19
    |
    = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
   --> crates/contracts/src/v0_7.rs:259:25
    |
259 |     Bytes::from_static(&__ENTRY_POINT_SIMULATIONS_V0_7_DEPLOYED_BYTECODE);
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0080]: evaluation of constant value failed
   --> crates/contracts/src/v0_7.rs:269:19
    |
269 |         Err(_) => panic!("Failed to decode call gas estimation proxy hex"),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Failed to decode call gas estimation proxy hex', crates/contracts/src/v0_7.rs:269:19
    |
    = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
   --> crates/contracts/src/v0_7.rs:274:25
    |
274 |     Bytes::from_static(&__CALL_GAS_ESTIMATION_PROXY_V0_7_DEPLOYED_BYTECODE);
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
error: could not compile `rundler-contracts` (lib) due to 2 previous errors

**Comment by dancoombs** [comment]
We should be fixing this soon. The workaround in the meantime is to install an older version of Foundry. Our CI uses 

`foundryup -i nightly-fe2acca4e379793539db80e032d76ffe0110298b`
